# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy-tests-linux-latest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          python3 -m pip install -r tests/requirements.txt
      - name: Build package
        run: python -m build
      - name: Install package
        run: pip install dist/*.whl
      - name: Run tests
        run: python setup.py test
        
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*
      
#   deploy-tests-windows-latest:
#     needs: deploy-tests-linux-latest
#     runs-on: windows-latest
    
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install build
#           python3 -m pip install -r tests\requirements.txt
#       - name: Install pep-tk from test.pypi
#         run: |
#           python3 -m pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple pep-tk
#       - name: Run tests
#         run: |
#           python3 setup.py test
