name: Run Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.2' # SemVer's version range syntax
#        env:
#          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
#          RUNNER_TOOL_CACHE: /opt/hostedtoolcache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - run:  python -m unittest discover -s tests -t tests

