name: Pull From Test Pypi

on:
  workflow_dispatch:
  
jobs:
  test-ubuntu-latest-install:
    name: Test installing from TestPyPi on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install TestPyPi Release
        run: pip install --index-url https://test.pypi.org/simple/  --extra-index-url https://pypi.org/simple pep-tk
      - name: Install test requirements
        run: pip install -r tests/requirements.txt
      - name: Run Tests on TestPyPi Release
        run:  python setup.py test
